apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-volume-claim
  labels:
    volume: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
